'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');
const { LAURA_CHARACTER_ID, lauraSeed, validateDeviceId, validateCharacterId } = require('./characterModel');

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function canAccess(character, deviceId) { return character && (character.isSystemCharacter || character.ownerDeviceId === deviceId); }
function scenarioFromRow(row) { return { id: row.id, characterId: row.character_id, name: row.name, description: row.description || '', openingBehavior: row.opening_behavior || '', roleInstructions: row.role_instructions || '', conversationGoals: row.conversation_goals, toneOverrides: row.tone_overrides, knowledgeFocus: row.knowledge_focus, appearanceOverride: row.appearance_override, memoryPolicy: row.memory_policy, enabled: row.enabled, createdAt: row.created_at, updatedAt: row.updated_at }; }
function characterFromRow(row) { return { id: row.id, ownerDeviceId: row.owner_device_id, name: row.name, slug: row.slug, shortDescription: row.short_description || '', status: row.status, identity: row.identity, appearance: row.appearance, family: row.family, personality: row.personality, communication: row.communication, knowledge: row.knowledge, behavior: row.behavior, settings: row.settings, defaultAvatarId: row.default_avatar_id || '', defaultVoiceId: row.default_voice_id || '', defaultRealtimeProvider: row.default_realtime_provider || 'grok', embodimentMode: row.embodiment_mode, isSystemCharacter: row.is_system_character, isPrivate: row.is_private, version: row.version, createdAt: row.created_at, updatedAt: row.updated_at }; }

class InMemoryCharacterStore {
    constructor(seed = {}) {
        this.available = true; this.persistence = 'memory';
        const laura = lauraSeed();
        this.characters = new Map([[laura.id, laura], ...(seed.characters || []).map((item) => [item.id, item])]);
        this.scenarios = new Map(Object.entries(seed.scenarios || {}));
        this.relationships = new Map(Object.entries(seed.relationships || {})); this.snapshots = new Map(Object.entries(seed.snapshots || {}));
    }
    async list(deviceId) { validateDeviceId(deviceId); return [...this.characters.values()].filter((item) => canAccess(item, deviceId)).map(clone); }
    async get(deviceId, characterId) { validateDeviceId(deviceId); validateCharacterId(characterId); const item = this.characters.get(characterId); return canAccess(item, deviceId) ? clone(item) : null; }
    async create(deviceId, profile) { validateDeviceId(deviceId); const now = new Date().toISOString(); const item = { id: crypto.randomUUID(), ownerDeviceId: deviceId, ...profile, isSystemCharacter: false, version: 1, createdAt: now, updatedAt: now }; this.characters.set(item.id, item); return clone(item); }
    async update(deviceId, characterId, profile) { const current = await this.get(deviceId, characterId); if (!current || current.isSystemCharacter) return null; const item = { ...current, ...profile, id: current.id, ownerDeviceId: current.ownerDeviceId, isSystemCharacter: false, version: current.version + 1, updatedAt: new Date().toISOString() }; this.characters.set(item.id, item); return clone(item); }
    async delete(deviceId, characterId) { const current = await this.get(deviceId, characterId); if (!current || current.isSystemCharacter) return false; this.characters.delete(characterId); this.scenarios.delete(characterId); for (const key of this.relationships.keys()) if (key.endsWith(`:${characterId}`)) this.relationships.delete(key); return true; }
    async listScenarios(deviceId, characterId) { if (!await this.get(deviceId, characterId)) return null; return clone(this.scenarios.get(characterId) || []); }
    async createScenario(deviceId, characterId, scenario) { if (!await this.get(deviceId, characterId)) return null; const now = new Date().toISOString(); const item = { id: crypto.randomUUID(), characterId, ...scenario, createdAt: now, updatedAt: now }; const items = this.scenarios.get(characterId) || []; items.push(item); this.scenarios.set(characterId, items); return clone(item); }
    async updateScenario(deviceId, characterId, scenarioId, scenario) { const items = await this.listScenarios(deviceId, characterId); if (!items) return null; const index = items.findIndex((item) => item.id === scenarioId); if (index < 0) return null; items[index] = { ...items[index], ...scenario, id: scenarioId, characterId, updatedAt: new Date().toISOString() }; this.scenarios.set(characterId, items); return clone(items[index]); }
    async deleteScenario(deviceId, characterId, scenarioId) { const items = await this.listScenarios(deviceId, characterId); if (!items) return false; const next = items.filter((item) => item.id !== scenarioId); this.scenarios.set(characterId, next); return next.length !== items.length; }
    async getRelationship(deviceId, characterId) { if (!await this.get(deviceId, characterId)) return null; const key = `${deviceId}:${characterId}`; return clone(this.relationships.get(key) || { deviceId, characterId, familiarity: 0, trustLevel: 0, humorLevel: .5, directnessPreference: .5, initiativePreference: .3, preferredResponseLength: 'short', allowedTopics: [], avoidedTopics: [], customData: {} }); }
    async updateRelationship(deviceId, characterId, relationship) { const current = await this.getRelationship(deviceId, characterId); if (!current) return null; const item = { ...current, ...relationship, deviceId, characterId, updatedAt: new Date().toISOString() }; this.relationships.set(`${deviceId}:${characterId}`, item); return clone(item); }
    async saveSnapshot(sessionId, deviceId, characterId, snapshot) { this.snapshots.set(sessionId, { sessionId, deviceId, characterId, snapshot: clone(snapshot) }); }
}

class FileCharacterStore extends InMemoryCharacterStore {
    constructor(filePath) { let seed = {}; try { seed = JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch (error) { if (error.code !== 'ENOENT') throw error; } super(seed); this.filePath = filePath; this.persistence = 'local-file'; }
    async persist() { await fs.promises.mkdir(path.dirname(this.filePath), { recursive: true }); const temporary = `${this.filePath}.${process.pid}.tmp`; const payload = { characters: [...this.characters.values()].filter((item) => item.id !== LAURA_CHARACTER_ID), scenarios: Object.fromEntries(this.scenarios), relationships: Object.fromEntries(this.relationships), snapshots: Object.fromEntries(this.snapshots) }; await fs.promises.writeFile(temporary, JSON.stringify(payload, null, 2), { encoding: 'utf8', mode: 0o600 }); await fs.promises.rename(temporary, this.filePath); }
    async create(...args) { const result = await super.create(...args); await this.persist(); return result; }
    async update(...args) { const result = await super.update(...args); if (result) await this.persist(); return result; }
    async delete(...args) { const result = await super.delete(...args); if (result) await this.persist(); return result; }
    async createScenario(...args) { const result = await super.createScenario(...args); if (result) await this.persist(); return result; }
    async updateScenario(...args) { const result = await super.updateScenario(...args); if (result) await this.persist(); return result; }
    async deleteScenario(...args) { const result = await super.deleteScenario(...args); if (result) await this.persist(); return result; }
    async updateRelationship(...args) { const result = await super.updateRelationship(...args); if (result) await this.persist(); return result; }
    async saveSnapshot(...args) { await super.saveSnapshot(...args); await this.persist(); }
}

class PostgresCharacterStore {
    constructor(connectionString) { this.pool = new Pool({ connectionString, max: 4, idleTimeoutMillis: 30_000 }); this.available = true; this.persistence = 'postgres'; }
    async list(deviceId) { validateDeviceId(deviceId); const result = await this.pool.query('SELECT * FROM laura_characters WHERE is_system_character=true OR owner_device_id=$1 ORDER BY is_system_character DESC, updated_at DESC', [deviceId]); return result.rows.map(characterFromRow); }
    async get(deviceId, id) { validateDeviceId(deviceId); validateCharacterId(id); const result = await this.pool.query('SELECT * FROM laura_characters WHERE id=$2 AND (is_system_character=true OR owner_device_id=$1)', [deviceId, id]); return result.rows[0] ? characterFromRow(result.rows[0]) : null; }
    values(deviceId, p) { return [deviceId,p.name,p.slug,p.shortDescription,p.status,p.identity,p.appearance,p.family,p.personality,p.communication,p.knowledge,p.behavior,p.settings,p.defaultAvatarId||null,p.defaultVoiceId||null,p.defaultRealtimeProvider,p.embodimentMode,p.isPrivate]; }
    async create(deviceId, p) { const result=await this.pool.query(`INSERT INTO laura_characters(owner_device_id,name,slug,short_description,status,identity,appearance,family,personality,communication,knowledge,behavior,settings,default_avatar_id,default_voice_id,default_realtime_provider,embodiment_mode,is_private) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *`,this.values(deviceId,p)); return characterFromRow(result.rows[0]); }
    async update(deviceId,id,p) { const result=await this.pool.query(`UPDATE laura_characters SET name=$3,slug=$4,short_description=$5,status=$6,identity=$7,appearance=$8,family=$9,personality=$10,communication=$11,knowledge=$12,behavior=$13,settings=$14,default_avatar_id=$15,default_voice_id=$16,default_realtime_provider=$17,embodiment_mode=$18,is_private=$19,version=version+1,updated_at=now() WHERE owner_device_id=$1 AND id=$2 AND is_system_character=false RETURNING *`,[deviceId,id,...this.values(deviceId,p).slice(1)]); return result.rows[0]?characterFromRow(result.rows[0]):null; }
    async delete(deviceId,id) { const result=await this.pool.query('DELETE FROM laura_characters WHERE owner_device_id=$1 AND id=$2 AND is_system_character=false',[deviceId,id]); return result.rowCount>0; }
    async listScenarios(deviceId,characterId) { if(!await this.get(deviceId,characterId))return null; const result=await this.pool.query('SELECT * FROM laura_character_scenarios WHERE character_id=$1 ORDER BY created_at',[characterId]); return result.rows.map(scenarioFromRow); }
    async createScenario(deviceId,characterId,s) { if(!await this.get(deviceId,characterId))return null; const result=await this.pool.query(`INSERT INTO laura_character_scenarios(character_id,name,description,opening_behavior,role_instructions,conversation_goals,tone_overrides,knowledge_focus,appearance_override,memory_policy,enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[characterId,s.name,s.description,s.openingBehavior,s.roleInstructions,s.conversationGoals,s.toneOverrides,s.knowledgeFocus,s.appearanceOverride,s.memoryPolicy,s.enabled]); return scenarioFromRow(result.rows[0]); }
    async updateScenario(deviceId,characterId,id,s) { if(!await this.get(deviceId,characterId))return null; const result=await this.pool.query(`UPDATE laura_character_scenarios SET name=$3,description=$4,opening_behavior=$5,role_instructions=$6,conversation_goals=$7,tone_overrides=$8,knowledge_focus=$9,appearance_override=$10,memory_policy=$11,enabled=$12,updated_at=now() WHERE id=$2 AND character_id=$1 RETURNING *`,[characterId,id,s.name,s.description,s.openingBehavior,s.roleInstructions,s.conversationGoals,s.toneOverrides,s.knowledgeFocus,s.appearanceOverride,s.memoryPolicy,s.enabled]); return result.rows[0]?scenarioFromRow(result.rows[0]):null; }
    async deleteScenario(deviceId,characterId,id) { if(!await this.get(deviceId,characterId))return false; const result=await this.pool.query('DELETE FROM laura_character_scenarios WHERE id=$2 AND character_id=$1',[characterId,id]); return result.rowCount>0; }
    async getRelationship(deviceId,characterId) { if(!await this.get(deviceId,characterId))return null; const result=await this.pool.query('SELECT * FROM laura_character_relationships WHERE device_id=$1 AND character_id=$2',[deviceId,characterId]); const x=result.rows[0]; return x?{deviceId,characterId,familiarity:Number(x.familiarity),trustLevel:Number(x.trust_level),humorLevel:Number(x.humor_level),directnessPreference:Number(x.directness_preference),initiativePreference:Number(x.initiative_preference),preferredResponseLength:x.preferred_response_length,allowedTopics:x.allowed_topics,avoidedTopics:x.avoided_topics,customData:x.custom_data}:{deviceId,characterId,familiarity:0,trustLevel:0,humorLevel:.5,directnessPreference:.5,initiativePreference:.3,preferredResponseLength:'short',allowedTopics:[],avoidedTopics:[],customData:{}}; }
    async updateRelationship(deviceId,characterId,x) { if(!await this.get(deviceId,characterId))return null; await this.pool.query(`INSERT INTO laura_character_relationships(device_id,character_id,familiarity,trust_level,humor_level,directness_preference,initiative_preference,preferred_response_length,allowed_topics,avoided_topics,custom_data,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,now()) ON CONFLICT(device_id,character_id) DO UPDATE SET familiarity=$3,trust_level=$4,humor_level=$5,directness_preference=$6,initiative_preference=$7,preferred_response_length=$8,allowed_topics=$9,avoided_topics=$10,custom_data=$11,updated_at=now()`,[deviceId,characterId,x.familiarity,x.trustLevel,x.humorLevel,x.directnessPreference,x.initiativePreference,x.preferredResponseLength,x.allowedTopics,x.avoidedTopics,x.customData]); return this.getRelationship(deviceId,characterId); }
    async saveSnapshot(sessionId,deviceId,characterId,snapshot){await this.pool.query('INSERT INTO laura_session_snapshots(session_id,device_id,character_id,character_snapshot) VALUES($1,$2,$3,$4) ON CONFLICT(session_id) DO NOTHING',[sessionId,deviceId,characterId,snapshot]);}
    async close(){await this.pool.end();}
}

function createCharacterStore({ databaseUrl='', characterFilePath='' }={}) { if(databaseUrl)return new PostgresCharacterStore(databaseUrl); return new FileCharacterStore(path.resolve(characterFilePath||path.join(process.cwd(),'.data','characters.json'))); }
module.exports={InMemoryCharacterStore,FileCharacterStore,PostgresCharacterStore,createCharacterStore};
