'use strict';

const test=require('node:test');const assert=require('node:assert/strict');
const {CharacterGenerationService,fillMissing,hasRealPersonCloneRequest}=require('../src/characters/generation/characterGenerationService');

function generated(name='Nora'){return{variants:[{summary:'Calm, observant travel companion',character:{name,shortDescription:'Calm travel companion',identity:{displayName:name,apparentAge:34,occupation:'travel writer',biography:'A fictional adult travel writer.',interests:['travel']},appearance:{apparentAge:34,presentation:'adult woman'},personality:{warmth:.7,directness:.6,humor:.5,curiosity:.8,confidence:.7,emotionalExpressiveness:.6,playfulness:.5,initiative:.5,formality:.3,patience:.8},communication:{responseLength:'short',vocabulary:'educated'},knowledge:{domains:[{name:'travel',level:'advanced'}]},behavior:{primaryRole:'travel guide',roles:['travel guide']},embodimentMode:'digital_explicit',defaultRealtimeProvider:'gemini'},scenarios:[{name:'Travel planning',description:'Plan a calm trip.'}]}]};}

test('generation returns editable unsaved structured drafts and is provider-independent',async()=>{const provider={name:'test-text',model:'fixture',available:true,async generateCharacter(){return generated();}};const service=new CharacterGenerationService(provider);const result=await service.generate({mode:'surprise_me'});assert.equal(result.saved,false);assert.equal(result.provider,'test-text');assert.equal(result.variants[0].character.identity.apparentAge,34);assert.equal(result.variants[0].scenarios.length,1);});
test('complete-missing preserves manually entered values',async()=>{const provider={name:'mock',available:true,async generateCharacter(){return generated();}};const service=new CharacterGenerationService(provider);const result=await service.generate({mode:'complete_missing',existingCharacter:{name:'My Nora',identity:{occupation:'architect'}},preserveExisting:true});assert.equal(result.variants[0].character.name,'My Nora');assert.equal(result.variants[0].character.identity.occupation,'architect');assert.match(result.variants[0].character.identity.biography,/fictional/);});
test('invalid generated output gets exactly one repair attempt',async()=>{let calls=0;const provider={name:'mock',available:true,async generateCharacter(){calls++;return{variants:[]};},async repairCharacter(){calls++;return generated('Repaired');}};const result=await new CharacterGenerationService(provider).generate({mode:'guided'});assert.equal(calls,2);assert.equal(result.repaired,true);assert.equal(result.variants[0].character.name,'Repaired');});
test('adult validation and real-person clone requests are rejected',async()=>{const provider={name:'mock',available:true,async generateCharacter(){const value=generated();value.variants[0].character.identity.apparentAge=17;value.variants[0].character.appearance.apparentAge=17;return value;}};await assert.rejects(()=>new CharacterGenerationService(provider).generate({mode:'surprise_me'}),{code:'character_must_present_as_adult'});assert.equal(hasRealPersonCloneRequest({hint:'Create an exact clone of my colleague'}),true);await assert.rejects(()=>new CharacterGenerationService(provider).generate({mode:'guided',guidedInput:{biographyHints:'Create an exact clone of my colleague'}}),{code:'real_person_cloning_not_allowed'});});
test('fillMissing does not overwrite non-empty manual arrays or scalar values',()=>{assert.deepEqual(fillMissing({name:'Manual',identity:{interests:['wine']}},{name:'Generated',identity:{interests:['travel'],biography:'Bio'}}),{name:'Manual',identity:{interests:['wine'],biography:'Bio'}});});
test('provider list items are bounded before strict character validation',async()=>{const value=generated();value.variants[0].character.identity.interests=['x'.repeat(180)];value.variants[0].scenarios[0].conversationGoals=['y'.repeat(180)];const provider={name:'mock',available:true,async generateCharacter(){return value;}};const result=await new CharacterGenerationService(provider).generate({mode:'surprise_me'});assert.equal(result.variants[0].character.identity.interests[0].length,120);assert.equal(result.variants[0].scenarios[0].conversationGoals[0].length,120);});
